config/routes.rb
Rails.application.routes.draw do
  resources :carts

  resources :prihlaskas

  resources :akces

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'akces#index'
  
  delete 'prihlaskas' => 'prihlaskas#destroy'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/akce.rb
class Akce < ActiveRecord::Base
	has_many :akce_prihlaskas
	has_many :prihlaskas, through: :akce_prihlaskas
	just_define_datetime_picker :termin

	validates :termin, presence: true

	before_destroy :ensure_not_referenced_by_any_prihlaska

	def ensure_not_referenced_by_any_prihlaska
		if prihlaskas.count.zero?
			return true
		else
			errors[:base] << 'K teto akci jsou prihlaseni zajemci'
			return false
		end
	end
end

app/models/akce_prihlaska.rb
class AkcePrihlaska < ActiveRecord::Base
  belongs_to :akce
  belongs_to :prihlaska
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :prihlaskas, :dependent => :destroy
end

app/models/prihlaska.rb
class Prihlaska < ActiveRecord::Base
  # belongs_to :cart
  has_many :akce_prihlaskas
  has_many :akces, through: :akce_prihlaskas
  accepts_nested_attributes_for :akces, reject_if: :all_blank
end

app/models/role_ucastnika.rb
class RoleUcastnika < ActiveRecord::Base
  has_many :prihlaskas
end

app/controllers/akces_controller.rb
class AkcesController < ApplicationController
  # include CurrentCart
  before_action :set_akce, only: [:show, :edit, :update, :destroy]
  # before_action :set_cart

  # GET /akces
  # GET /akces.json
  def index
    @akces = Akce.all
  end

  # GET /akces/1
  # GET /akces/1.json
  def show
  end

  # GET /akces/new
  def new
    @akce = Akce.new
  end

  # GET /akces/1/edit
  def edit
  end

  # POST /akces
  # POST /akces.json
  def create
    @akce = Akce.new(akce_params)

    respond_to do |format|
      if @akce.save
        format.html { redirect_to @akce, notice: 'Akce was successfully created.' }
        format.json { render :show, status: :created, location: @akce }
      else
        format.html { render :new }
        format.json { render json: @akce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akces/1
  # PATCH/PUT /akces/1.json
  def update
    respond_to do |format|
      if @akce.update(akce_params)
        format.html { redirect_to @akce, notice: 'Akce was successfully updated.' }
        format.json { render :show, status: :ok, location: @akce }
      else
        format.html { render :edit }
        format.json { render json: @akce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akces/1
  # DELETE /akces/1.json
  def destroy
    @akce.destroy
    respond_to do |format|
      format.html { redirect_to akces_url, notice: 'Akce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akce
      @akce = Akce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def akce_params
      params.require(:akce).permit(:id, :termin, :popis, :cena, :misto_srazu, :termin_date, 
        :termin_time_hour, :termin_time_minute, :_destroy)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/carts_controller.rb
class CartsController < InheritedResources::Base
	# include CurrentCart
	# before_action :set_cart

	# def show
	# 	begin
	# 		@cart = Cart.find([:id])
	# 	rescue ActiveRecord::RecordNotFound
	# 		logger.error "Attempt to access invalid cart #{params[:id]}"
	# 		redirect_to root_url, :notice => 'Neplatný košík'
	# 	else
	# 		respond_to do |format|
	# 			format.html # show.html.erb
	# 			format.json { render json: @cart }
	# 		end
	# 	end
	# end
	def update
		respond_to do |format|
			if @cart.update(cart_params)
				format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
				format.js
				format.json { render :show, status: :ok, location: @cart }
			else
				format.html { render :edit }
				format.json { render json: @cart.errors, status: :unprocessable_entity }
			end
		end
	end

	private

	def cart_params
		params.require(:cart).permit(:jmeno, :prijmeni, :vzkaz, :email, :telefon, :potvrzeno)
	end


end

app/controllers/concerns/current_cart.rb
module CurrentCart
	extend ActiveSupport::Concern

	  private

	  def set_cart
	  	@cart = Cart.find(session[:cart_id])
	  rescue ActiveRecord::RecordNotFound
	  	@cart = Cart.create
	  	session[:cart_id] = @cart.id
	  end
end

app/controllers/prihlaskas_controller.rb
class PrihlaskasController < ApplicationController
  # include CurrentCart
  # before_action :set_cart, only: [:create, :destroy]
  # before_action :set_prihlaska, only: [:show, :edit, :update]

  # GET /prihlaskas
  # GET /prihlaskas.json
  def index
    @prihlaskas = Prihlaska.all
  end

  # GET /prihlaskas/1
  # GET /prihlaskas/1.json
  def show
  end

  # GET /prihlaskas/new
  def new
    @prihlaska = Prihlaska.new
    @akces = Akce.find(params[:akce])
  end

  # GET /prihlaskas/1/edit
  def edit
  end

  # POST /prihlaskas
  # POST /prihlaskas.json
  def create
    # akce = Akce.find(params[:checkbox])
    @prihlaska = Prihlaska.new(prihlaska_params)

    respond_to do |format|
      if @prihlaska.save
        format.js
        format.html { redirect_to(root_url, notice: 'Úspěšně jste se přihlásili!') }
        format.json { render :show, status: :created, location: @prihlaska }
      else
        format.html { render :new }
        format.json { render json: @prihlaska.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prihlaskas/1
  # PATCH/PUT /prihlaskas/1.json
  def update
    respond_to do |format|
      if @prihlaska.update(prihlaska_params)
        format.html { redirect_to @prihlaska, notice: 'Prihlaska was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @prihlaska }
      else
        format.html { render :edit }
        format.json { render json: @prihlaska.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prihlaskas/1
  # DELETE /prihlaskas/1.json
  def destroy
    # find current cart
    # find akce_id which i want to destroy = akceid
    # destroy all prihlaskas with akce_id = akceid and cart_id = current_cart.id
    # @aktual_prihlaska = Prihlaska.where(cart_id: @cart.id)
    prihlaskas_id = Prihlaska.find_by(akce_id: params[:akce_id]).id
    Prihlaska.destroy(prihlaskas_id)
    # @prihlaska.destroy

    respond_to do |format|
      # format.html { redirect_to prihlaskas_url, notice: 'Prihlaska was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  # def destroy_prihlaska_in_cart
  #   prihlaskas_id = Prihlaska.where(cart_id: @cart.id).id
  #   Prihlaska.destroy(prihlaskas_id)

  #   respond_to do |format|
  #     format.html { redirect_to prihlaskas_url, notice: 'Prihlaska was successfully destroyed.' }
  #     format.js
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_prihlaska
      # @prihlaska = Prihlaska.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prihlaska_params
      params.require(:prihlaska).permit(:jmeno, :prijmeni, :email, :telefon, :role, :vozickar, :prukaz, :vzkaz, akce_ids: [])
    end
end

app/helpers/akces_helper.rb
module AkcesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/prihlaskas_helper.rb
module PrihlaskasHelper
end

app/views/akces/_form.html.erb
<%= form_for @akce, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :termin, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :termin, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :popis, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :popis, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cena, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :cena, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :misto_srazu, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :misto_srazu, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  akces_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/akces/edit.html.erb
<%- model_class = Akce -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Akce %></h1>
</div>
<%= render :partial => 'form' %>

app/views/akces/index.html.erb
<%- model_class = Akce -%>
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1 class='center'><%=t '.title', :default => Akce %></h1>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12"><h2>Aktuální akce</h2></div>
  </div>
  <div class="row">
    <div class="container border-around col-md-12">
		<%= form_tag({controller: "prihlaskas", action: "new"}, method: "get", :html => { :class => 'form-horizontal form-model' }) do |f| %>
      <table class="table">
        <thead>
          <tr>
            <th>Zúčastním se</th>
            <th>Termín</th>
            <th>Popis</th>
            <th>Cena</th>
            <th>Místo srazu</th>
          </tr>
        </thead>
        <tbody>
          <% @akces.each do |akce| %>
          <% if akce.termin >= Date.today %>
          <tr class="center">
            <td class="col1">
              <%= check_box_tag 'akce[]', akce.id, checked = false %>
              <%#= check_box_tag 'checkbox', akce.id, checked = false, :data => {:remote => true, 
              url: url_for(controller: :prihlaskas, action: :create, akce_id: akce), method: :post}, :class => 'checkbox' %>
              <%#= button_to 'Pridat do prihlasky', prihlaskas_path(akce_id: akce), :remote => true %>
              <%#= button_to 'Remove from prihlaska',  prihlaskas_path(cart_id: @cart.id, akce_id: akce), :method => :delete, :remote => true %>
              <%#= check_box_tag 'checkboxa', akce.id, checked = false, :data => {:remote => true, 
              url: url_for(controller: :prihlaskas, action: :destroy, cart_id: @cart.id, akce_id: akce), method: :delete}, :class => 'checkboxa' %>
            </td>
            <td><%= akce.termin.strftime('%e.%-m.%Y - %k:%M') %></td>
            <td><%= akce.popis %></td>
            <td><%= akce.cena %></td>
            <td><%= akce.misto_srazu %></td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="center">
          <button class='btn btn-primary'>Přihlásit se na zaškrtnuté Humry</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row"></div>
  <div class="row">
    <div class="col-md-12">
      <h2>Proběhlé akce</h2>
      <div class="container border-around col-md-12">
        <table class="table">
          <thead>
            <tr>
              <th>Termín</th>
              <th>Popis</th>
              <th>Cena</th>
              <th>Místo srazu</th>
            </tr>
          </thead>
          <tbody>
            <% @akces.each do |akce| %>
            <% if akce.termin < Date.today %>
            <tr class="center">
              <td><%= akce.termin.strftime('%e.%-m.%Y - %k:%M') %></td>
              <td><%= akce.popis %></td>
              <td><%= akce.cena %></td>
              <td><%= akce.misto_srazu %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/akces/new.html.erb
<%- model_class = Akce -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Akce %></h1>
</div>
<%= render :partial => 'form' %>

app/views/akces/show.html.erb
<%- model_class = Akce -%>
<div class="page-header">
  <h1><%=t '.title', :default => Akce %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:termin) %></dt>
      <dd><pre class="prettyprint"><%= @akce.termin %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:popis) %></dt>
      <dd><pre class="prettyprint"><%= @akce.popis %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cena) %></dt>
      <dd><pre class="prettyprint"><%= @akce.cena %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:misto_srazu) %></dt>
      <dd><pre class="prettyprint"><%= @akce.misto_srazu %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              akces_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_akce_path(@akce), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              akce_path(@akce),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/carts/_cart.html.erb
	<% if cart.prihlaskas.any? %>
	<ul>
		<%= render(cart.prihlaskas) %>
	</ul>
	<div class="row">
		<div class="col-md-offset-6 col-md-6">
			<%#= button_to 'Zrušit přihlášky', @cart, method: :delete, confirm: "Smazat všechny přihlášky?" %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			Prosím zadejte Vaše údaje a potvrďte přihlášení.
		</div>
	</div>


	<%= form_for @cart, :html => { :class => 'form-horizontal form-model' } do |f| %>
	<div class="row">
		<div class="form-group">
			<%#= f.label :jmeno, 'Jméno:', :class => 'control-label col-md-2' %>
			<div class="col-md-10 col-md-offset-1">
				<%= f.text_field :jmeno, placeholder: 'Jméno', :class => 'text-field form-control' %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<%#= f.label :prijmeni, 'Příjmení:', :class => 'control-label col-md-2' %>
			<div class="col-md-10 col-md-offset-1">
				<%= f.text_field :prijmeni, placeholder: 'Příjmení', :class => 'text-field form-control' %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<%#= f.label :email, :class => 'control-label col-md-2' %>
			<div class="col-md-10 col-md-offset-1">
				<%= f.text_field :email, placeholder: 'E-mail', :class => 'text-field form-control' %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<%#= f.label :telefon, :class => 'control-label col-md-2' %>
			<div class="col-md-10 col-md-offset-1">
				<%= f.text_field :telefon, placeholder: 'Telefonní číslo', :class => 'text-field form-control' %>
			</div>
		</div>
	</div>


	<div class="row">
		<div class="form-group">
			<%= f.label :role, 'Na humr jdu jako člověk:', :class => 'control-label col-md-6' %>
			<div class="col-md-6">
				<%= f.select :role, options_for_select(['asistující','asistovaný']), :class => 'select form-control' %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="form-group">
			<%= f.label :vozickar, 'Pojedu na vozíku:', :class => 'control-label col-md-6' %>
			<div class="col-md-1">
				<%= f.check_box :vozickar, :class => 'checkbox form-control' %>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="form-group">
			<%= f.label :prukaz, 'Mám průkaz:', :class => 'control-label col-md-6' %>
			<div class="col-md-6">
				<%= f.select :prukaz, options_for_select(['žádný','ZTP', 'ZTP/P']), :class => 'select form-control' %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="form-group">
			<%#= f.label :vzkaz, :class => 'control-label col-md-2' %>
			<div class="col-md-10 col-md-offset-1">
				<%= f.text_area :vzkaz, placeholder: 'Zde nám můžete zanechat vzkaz', :class => 'text-field form-control' %>
			</div>
		</div>
	</div>
	<div class="form-group">
		<%= f.hidden_field :potvrzeno, :class => 'text-field form-control', value: true %>
	</div>
	<div class="row">
		<div class="form-group">
			<div class='col-md-offset-2 col-md-10'>
				<%= f.submit 'Přihlásit se!', :class => 'btn btn-primary' %>
				<button type="button" class="btn btn-default" data-dismiss="modal">
					Close
				</button>
				<%#= link_to t('.cancel', :default => t("helpers.links.cancel")), carts_path, :class => 'btn btn-default' %>
			</div>
		</div>
	</div>
	<% end %>
</div>

<% else %>
Na žádný Humr jste se nepřihlásili! Vyberte si některé z aktuálních akcí.
<% end %>

app/views/carts/_cartform.html.erb
<br>
<%= form_for @cart, :html => { :class => 'form-horizontal form-model' } do |f| %>
<div class="form-group">
	<%= f.label :jmeno, :class => 'control-label col-md-2' %>
	<div class="col-md-8">
		<%= f.text_field :jmeno, :class => 'text-field form-control' %>
	</div>
</div>
<div class="form-group">
	<%= f.label :prijmeni, :class => 'control-label col-md-2' %>
	<div class="col-md-8">
		<%= f.text_field :prijmeni, :class => 'text-field form-control' %>
	</div>
</div>
<div class="form-group">
	<%= f.label :email, :class => 'control-label col-md-2' %>
	<div class="col-md-8">
		<%= f.text_field :email, :class => 'text-field form-control' %>
	</div>
</div>
<div class="form-group">
	<%= f.label :telefon, :class => 'control-label col-md-2' %>
	<div class="col-md-8">
		<%= f.text_field :telefon, :class => 'text-field form-control' %>
	</div>
</div>
<div class="form-group">
	<%= f.label :vzkaz, :class => 'control-label col-md-2' %>
	<div class="col-md-8">
		<%= f.text_field :vzkaz, :class => 'text-field form-control' %>
	</div>
</div>
<div class="form-group">
	<div class="col-md-8">
	<%= f.hidden_field :potvrzeno, :class => 'text-field form-control', value: true %>
	</div>
</div>
<div class="form-group">
	<div class='col-md-offset-2 col-md-10'>
		<%= f.submit nil, :class => 'btn btn-primary' %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<%#= link_to t('.cancel', :default => t("helpers.links.cancel")),
		carts_path, :class => 'btn btn-default' %>
	</div>
</div>
<% end %>

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Přihláška</h2>
	<%= render @cart %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RamusHumr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body><%= bootstrap_flash %>

<%= yield %>

</body>
</html>

app/views/prihlaskas/_form.html.erb
<%= form_for @prihlaska, :html => { :class => 'form-horizontal' } do |f| %>
<div class="col-md-12">
	<ul>
		<% @akces.each do |akce| %>
		<li><%= akce.termin.strftime('%e.%-m.%Y - %k:%M') %>, <%= akce.popis %></li>
		<% end %>
	</ul>
</div>
<div class="form-group nomargin">
	<%#= f.label :jmeno, 'Jméno:', :class => 'control-label col-md-2' %>
	<%= f.text_field :jmeno, placeholder: 'Jméno', :class => 'text-field form-control' %>
</div>
<div class="form-group nomargin">
	<%#= f.label :prijmeni, 'Příjmení:', :class => 'control-label col-md-2' %>
	<%= f.text_field :prijmeni, placeholder: 'Příjmení', :class => 'text-field form-control' %>
</div>
<div class="form-group nomargin">
	<%#= f.label :email, :class => 'control-label col-md-2' %>
	<%= f.text_field :email, placeholder: 'E-mail', :class => 'text-field form-control' %>
</div>
<div class="form-group nomargin">
	<%#= f.label :telefon, :class => 'control-label col-md-2' %>
	<%= f.text_field :telefon, placeholder: 'Telefonní číslo', :class => 'text-field form-control' %>
</div>


<div class="form-group nomargin">
	<div class="col-md-3">
	</div>
	<%= f.label :role, 'Na humru se chci:', :class => 'control-label col-md-4' %>
	<div class="col-md-5">
		<%= f.select :role, options_for_select(['bavit','bavit a asistovat']), :class => 'select form-control' %>
	</div>
</div>

<div class="form-group nomargin">
	<div class="col-md-3">
	</div>
	<%= f.label :vozickar, 'Pojedu na vozíku:', :class => 'control-label col-md-4' %>
	<div class="col-md-1">
		<%= f.check_box :vozickar, :class => 'checkbox form-control' %>
	</div>
</div>

<div class="form-group nomargin">
	<div class="col-md-3">
	</div>
	<%= f.label :prukaz, 'Mám průkaz:', :class => 'control-label col-md-4' %>
	<div class="col-md-5">
		<%= f.select :prukaz, options_for_select(['žádný','ZTP', 'ZTP/P']), :class => 'select form-control' %>
	</div>
</div>

<div class="form-group nomargin">
	<%#= f.label :vzkaz, :class => 'control-label col-md-2' %>
	<%= f.text_area :vzkaz, placeholder: 'Zde nám můžete zanechat vzkaz', :class => 'text-field form-control' %>
</div>

<% @akces.each do |akce| %>
	<%= f.hidden_field :akce_ids, multiple: true, value: akce.id %>
<% end %>

<div class="form-group nomargin">
	<div class="col-md-7">
	</div>
	<div class="col-md-5">
		<%= f.submit 'Přihlásit se!', :class => 'btn btn-primary' %>
	</div>
	<%#= link_to t('.cancel', :default => t("helpers.links.cancel")), carts_path, :class => 'btn btn-default' %>
</div>
<% end %>

app/views/prihlaskas/_prihlaska.html.erb
<div class="row">
	<div class="col-md-12">
		<li> <%= prihlaska.akce.termin.strftime('%e.%-m.%Y - %k:%M') %>, <%= prihlaska.akce.popis %> </li>
	</div>
</div>

app/views/prihlaskas/create.js.erb
$('#akce').html("<%= escape_javascript render(@cart) %>");

app/views/prihlaskas/destroy.js.erb
$('#prihlaseneakce').html("<%= j render(@cart) %>");

app/views/prihlaskas/edit.html.erb
<%- model_class = Prihlaska -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Prihlaska %></h1>
</div>
<%= render :partial => 'form' %>

app/views/prihlaskas/index.html.erb
<%- model_class = Prihlaska -%>
<div class="page-header">
  <h1><%=t '.title', :default => Prihlaska %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>AKCE ID</th>
      <th>CART ID</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @prihlaskas.each do |prihlaska| %>
      <tr>
        <td><%= prihlaska.id %></td>
        <td><%= prihlaska.akce_id %></td>
        <td><%= prihlaska.cart_id %></td>
        <td><%=l prihlaska.created_at, format: :long %></td>
        <td>
          <%= link_to prihlaska_path(prihlaska), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to prihlaska_path(prihlaska), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_prihlaska_path,
            :class => 'btn btn-primary' %>

app/views/prihlaskas/new.html.erb
<%- model_class = Prihlaska -%>
<div class="row">
	<div class="col-md-12">	
		<div class="page-header">
			<h1 class="center">
				Přihláška
			</h1>
		</div>
	</div>	
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render :partial => 'form' %>
	</div>
</div>